import React from 'react'
import { AiOutlineAccountBook } from 'react-icons/ai'
const Service = () => {
  return (
    <div className='grid grid-col grid-cols-1 md:grid-cols-2 lg:grid-cols-3 justify-items-center place-items-center gap-10 min-h-screen mx-auto p-5'>
        <div className='flex flex-col justify-center'>
            <AiOutlineAccountBook className='w-8 h-8'/>
            <h3>Proactive blocklist tracking</h3>
            <p className='max-w-sm'>Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend.</p>
        </div>
        <div className='flex flex-col justify-center'>
            <AiOutlineAccountBook className='w-8 h-8'/>
            <h3>Proactive blocklist tracking</h3>
            <p className='max-w-sm'>Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend.</p>
        </div>
        <div className='flex flex-col justify-center'>
            <AiOutlineAccountBook className='w-8 h-8'/>
            <h3>Proactive blocklist tracking</h3>
            <p className='max-w-sm'>Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend.</p>
        </div>
        <div className='flex flex-col justify-center'>
            <AiOutlineAccountBook className='w-8 h-8'/>
            <h3>Proactive blocklist tracking</h3>
            <p className='max-w-sm'>Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend.</p>
        </div>
        <div className='flex flex-col justify-center'>
            <AiOutlineAccountBook className='w-8 h-8'/>
            <h3>Proactive blocklist tracking</h3>
            <p className='max-w-sm'>Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend.</p>
        </div>
        <div className='flex flex-col justify-center'>
            <AiOutlineAccountBook className='w-8 h-8'/>
            <h3>Proactive blocklist tracking</h3>
            <p className='max-w-sm'>Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend.</p>
        </div>
    </div>
  )
}

export default Service